eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 900000
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000
        cookie-name: refresh-jwt-cookie