server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:3678/auth_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-Auto: create-drop
    defer-datasource-initialization: true
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql